# Generated by Django 3.2.7 on 2021-10-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, help_text='16 digit number', max_length=16)),
                ('cvv', models.CharField(blank=True, help_text='3 digit number at the back of your card', max_length=3)),
                ('exp', models.CharField(help_text='Expiry date of card', max_length=5)),
            ],
        ),
    ]
