# Generated by Django 3.2.7 on 2021-10-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0024_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='paystack_order_id',
            new_name='order_reference',
        ),
    ]
