# Generated by Django 3.2.7 on 2021-10-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0025_rename_paystack_order_id_orderhistory_order_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
