# Generated by Django 3.2.7 on 2021-10-29 04:41

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(default=orders.models.random_numbers, max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Out for Delivery'), (3, 'Delivered')], default='Pending', max_length=50),
        ),
    ]
